### PR TITLE
replace sprig with sprout

### PR DESCRIPTION
**Pull request by abs3ntdev**
switches from [sprig](https://github.com/Masterminds/sprig) to [sprout](https://github.com/go-sprout/sprout)

### CODE REVIEW

**Comment by jackc** [comment]
So Sprig isn't getting updated much anymore? 🤔  But sprout seems fairly new. I suppose could move at some point, but I think I'd prefer to let sprout get more established before taking it on as a dependency.

**Comment by elee1766** [comment]
sprig isn't updated, the bigger issue actually is https://github.com/Masterminds/sprig/pull/377

**Comment by jackc** [comment]
Hmmm.... I'm not opposed to moving eventually, but I'm wary of depending on such a new project. Since sprout is a compatible fork would it be possible for those who need it right away to use a replace directive in the go.mod file?

**Comment by elee1766** [comment]
just tried, it's not working at least for my set of dependencies. 

luckily we aren't using go install for releases, so it's not a super big deal with the replace directive for mergo, but it would really be nice not to have any replace directives (this is our only one). 

helm is still using sprig, and mattfarina seems to still be maintaining helm - so maybe he will run into the dependency issue at some point and update sprig.

**Comment by jackc** [comment]
It looks like sprig is active again and https://github.com/Masterminds/sprig/pull/377 is resolved.

**Comment by elee1766** [comment]
awesome. @abs3ntdev we should close this and pr the upgrade, making sure it fixes our issues.

**Pull request closed without merging**
